"use strict";
function updateUI(){$('#mana').textContent=Math.floor(mana);$('#hp').textContent=Math.ceil(keep);$('#kills').textContent=kills;$('#time').textContent=fmt(elapsed);$('#deployed').textContent=deployments;let pct=clamp(keep,0,100),fill=$('#keepFill');fill.style.width=pct+'%';fill.style.background=pct>60?'#54b84a':pct>30?'#d3a937':'#cf3d35';$$('.unit').forEach(b=>b.disabled=mana<COST[b.dataset.type])}
function reset(){spawn.seen={};commandMode=null;mana=4;keep=100;kills=0;elapsed=0;deployments=0;ended=false;crumbling=false;crumbleTime=0;faceMood='normal';faceUntil=0;keepHitBurst=0;manaTick=0;spawnTick=0;units=[];enemies=[];towers=[];shots=[];parts=[];deaths=[];hitStopTimer=0;cameraShake=0;devPaused=false;last=performance.now();select('warrior');updateUI()}
async function askName(){await ready();sfx.title();setTimeout(speakTitle,220);toast('DEFEND THE KEEP!');$('#start').disabled=true;setTimeout(()=>{$('#playerName').value=playerName;$('#nameScreen').classList.remove('hidden');$('#start').disabled=false;setTimeout(()=>$('#playerName').focus(),80)},1450)}function begin(){playerName=($('#playerName').value||'Andy').trim().slice(0,18)||'Andy';localStorage.setItem('defendKeepPlayer',playerName);$('#nameScreen').classList.add('hidden');reset();started=true;$('#title').classList.add('hidden');$('#over').classList.add('hidden');startMusic()}
function showHall(){let book=JSON.parse(localStorage.getItem('defendKeepHeroesV02')||'[]').sort((a,b)=>(b.kills||0)-(a.kills||0)).slice(0,10);localStorage.setItem('defendKeepHeroesV02',JSON.stringify(book));$('#heroList').innerHTML=book.length?book.map((h,i)=>`<div class="entry">${h.portrait?`<img src="${h.portrait}" alt="Portrait" style="width:64px;height:64px;image-rendering:pixelated;float:left;margin:0 10px 8px 0;border:3px solid #8d693d;background:#78925b">`:`<div style="width:64px;height:64px;float:left;margin:0 10px 8px 0;border:3px solid #8d693d;background:#78925b;display:grid;place-items:center;font-size:30px">⚔️</div>`}<b>#${i+1} ${h.name}</b><br>${h.kills} kills · ${h.date}${h.king?`<br>Proudly served King ${h.king}`:''}<small>${h.story}</small><div style="clear:both"></div></div>`).join(''):`<div class="empty">No heroes are recorded yet.<br><br>Every 100th deployment summons one.</div>`;$('#hall').classList.remove('hidden')}
$('#start').onpointerdown=askName;$('#nameGo').onpointerdown=begin;$('#playerName').addEventListener('keydown',e=>{if(e.key==='Enter')begin()});$('#again').onpointerdown=()=>{ready();reset();started=true;$('#over').classList.add('hidden');startMusic()};$('#backTitle').onpointerdown=()=>{stopMusic();started=false;$('#over').classList.add('hidden');$('#title').classList.remove('hidden')};$('#hallOpen').onpointerdown=()=>{ready();showHall()};$('#hallOver').onpointerdown=showHall;$('#hallClose').onpointerdown=()=>$('#hall').classList.add('hidden');let titleSoundDone=false;$('#title').addEventListener('pointerdown',async()=>{if(!titleSoundDone){await ready();sfx.title();setTimeout(speakTitle,160);titleSoundDone=true}},{once:true});
$('#manaStat').onpointerdown=async()=>{await ready();mana+=100;toast('SECRET TREASURY: +100 COINS');sfx.promote();updateUI()};
$('#musicToggle').onpointerdown=()=>{ready();musicOn=!musicOn;$('#musicToggle').classList.toggle('off',!musicOn);$('#musicToggle').textContent=musicOn?'♫':'♪';if(musicOn&&started&&!ended)startMusic();else stopMusic()};
let lastRenderError='',fpsSmooth=60;function loop(now){let dt=Math.min((now-last)/1000,.035);last=now;fpsSmooth=fpsSmooth*.9+(1/Math.max(dt,.001))*.1;devFps=fpsSmooth;try{if(hitStopTimer>0){hitStopTimer=Math.max(0,hitStopTimer-dt);updateJuice(dt*.25)}else if(!devPaused)update(dt);else updateJuice(dt);draw();lastRenderError=''}catch(err){console.error(err);if(String(err)!==lastRenderError){lastRenderError=String(err);toast('DISPLAY ERROR: '+(err.message||'unknown'))}}requestAnimationFrame(loop)}resize();reset();requestAnimationFrame(loop);
